# Generated by Django 5.1.10 on 2025-06-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='aggregate_rating',
            new_name='rating',
        ),
    ]
