# Generated by Django 5.1.10 on 2026-01-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_review_options_review_review_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='customer_name',
            field=models.CharField(max_length=254),
        ),
    ]
