# Generated by Django 5.1.10 on 2026-01-09 22:40

from django.db import migrations


def delete_reviews_with_null_order_and_null_user(apps, schema_editor):
    Review = apps.get_model('products', 'Review')
    Review.objects.filter(order__isnull=True).delete()
    Review.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_review_options_remove_review_customer_name_and_more'),
    ]

    operations = [
         migrations.RunPython(delete_reviews_with_null_order_and_null_user),
    ]
