# Generated by Django 5.1.10 on 2026-01-04 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_review_customer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_update',
        ),
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
    ]
